### ISSUE TITLE
请问现在只支持ubutu操作系统了吗？

### ISSUE THREAD

**Issue by miaoshououdezhi** [Naochen2799/Lastest-Kernel-BBR3#3]
之前使用almalinux还能更新的，现在使用那个脚本已经无法获取更新了。

**Comment by Naochen2799** [comment]
softprops/action-gh-release@master存在异常，无法将编译出来的deb包上传至release，正在查看官方文档处理中

**Comment by miaoshououdezhi** [comment]
哦哦，好的了解了。感谢您的付出！
